---

- name: Django app | Source code | Make sure directory exists
  tags: [django-app-code, django-initial]
  file:
    path: "{{ django_root }}"
    state: directory

- name: Django app | Source code | Push code
  tags: [django-app-code]
  when: django_push_mode == "sync"
  synchronize:
    src: "{{ django_local_repo_root }}"
    dest: "{{ django_root }}"
  notify:
    - python code updated
  become: true

- name: Django app | Source code | Push code| Make pushed code owned by user
  tags: [django-app-code]
  when: django_push_mode == "sync"
  command: "chown -R {{ user }}:{{ group }} {{ django_app_root }}"
  notify:
    - python code updated
  become: true
  become_user: root

- name: Django app | Dependencies | Pip | Make sure itself is installed
  tags: [django-dependencies, django-initial]
  apt: name=python3-pip state=installed
  become: true
  become_user: root

- name: Django app | Dependencies | Pip | Make sure itself is latest
  tags: [django-dependencies, django-initial]
  pip: executable=pip3 name=pip state=latest
  become: true
  become_user: root

- name: Django app | Dependencies | Custom Pip requirements
  tags: [django-dependencies]
  pip: executable=pip3 requirements={{ django_pip_dependencies }}
  become: true
  become_user: root
  notify:
    - python code updated

- name: Django app | Dependencies | Debug requirements
  tags: [django-dependencies, django-initial]
  when: django_debug|bool
  pip: executable=pip3 name={{ item }} state=present
  with_items:
    - django-sslserver
    - Werkzeug
    - django-extensions
  become: true
  become_user: root
  notify:
    - python code updated

- name: Django app | Dependencies | CORS requirements
  tags: [django-dependencies]
  when: django_cors is defined
  pip: executable=pip3 name=django-cors-headers state=present
  become: true
  become_user: root
  notify:
    - python code updated

- name: Django app | Dependencies | Memcached | Install Apt libs
  tags: [django-dependencies, django-initial]
  when: django_memcached_locations is defined
  apt: name={{ item }} state=present
  with_items:
    - libsasl2-dev
    - zlib1g-dev
    - libmemcached-dev
  become: true

- name: Django app | Dependencies | Memcached | Install Pylibmc
  tags: [django-dependencies, django-initial]
  when: django_memcached_locations is defined
  pip: executable=pip3 name=pylibmc state=present
  become: true
  notify:
    - python code updated

- name: Django app | Source code | Notify handlers about changed code
  tags: [django-app-code, django-settings]
  when: django_push_mode == "none"
  command: /bin/true
  notify:
    - python code updated

- name: Django app | Settings | Upload settings template
  tags: [django-settings]
  template:
    src=templates/django_settings.py.j2
    dest={{ django_app_root }}/{{ django_project_module }}/settings.py
  notify:
    - python code updated

- name: Django app | Settings | Append extra settings
  tags: [django-settings]
  blockinfile:
    path: "{{ django_app_root }}/{{ django_project_module }}/settings.py"
    block: "{{ django_settings_extra }}"

- name: Django app | Deployment checklist
  django_manage:
    app_path={{ django_app_root }}
    command="check --deploy"
  ignore_errors: yes

- name: Django app | Migrate database
  tags: [django-migrations]
  django_manage:
    app_path={{ django_app_root }}
    command=migrate

- name: Django app | Collect static assets
  tags: [django-static]
  django_manage:
    app_path={{ django_app_root }}
    command=collectstatic

- name: Django app | Load initial data
  tags: [django-loaddata]
  when: django_initial_data_fixture.load|bool
  django_manage:
    app_path={{ django_app_root }}
    command="loaddata {{ django_initial_data_fixture.path }}"
